version: "3.9"

services:

  php:
    build:
      context: .
      dockerfile: dockerfiles/dockerfile

    container_name: php

    working_dir: /var/www/html

    volumes:
      - ./:/var/www/html

    depends_on:
      - mysql

  nginx:

    image: nginx:latest

    container_name: laravel_nginx

    ports:
      - "8000:80"

    volumes:
      - ./:/var/www/html
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php

  mysql:

    image: mysql:8.0

    container_name: laravel_mysql

    restart: unless-stopped

    environment:

      MYSQL_DATABASE: hieuboss

      MYSQL_ROOT_PASSWORD: root

      MYSQL_USER: hieu

      MYSQL_PASSWORD: hieu

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:

  mysql_data:
